# Generated by Django 3.0.14 on 2021-06-27 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('img', models.CharField(default='', max_length=1500)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
